version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "battleship"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    env_file:
      - ../.env
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data:
