// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"time"
)

type Game struct {
	ID                int64     `json:"id"`
	Player1ID         int64     `json:"player1Id"`
	Player2ID         int64     `json:"player2Id"`
	Player1RankChange int64     `json:"player1RankChange"`
	Player2RankChange int64     `json:"player2RankChange"`
	CreatedAt         time.Time `json:"createdAt"`
	FinishedAt        time.Time `json:"finishedAt"`
}

type User struct {
	ID           int64  `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"passwordHash"`
	Rank         int64  `json:"rank"`
}

type UserFriend struct {
	User1ID int64 `json:"user1Id"`
	User2ID int64 `json:"user2Id"`
}
