// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"context"
)

type Querier interface {
	CreateGame(ctx context.Context, arg CreateGameParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetGameById(ctx context.Context, id int64) (Game, error)
	GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]GetLeaderboardRow, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserFriends(ctx context.Context, user1ID int64) ([]User, error)
	GetUserGameHistoryPaged(ctx context.Context, arg GetUserGameHistoryPagedParams) ([]Game, error)
	UpdateUserRank(ctx context.Context, arg UpdateUserRankParams) error
}

var _ Querier = (*Queries)(nil)
